name: test

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [ubuntu-latest]
    environment: test

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: create .env file
        run: |
          touch .env
          echo 'AWS_STORAGE_BUCKET_NAME=${{ secrets.AWS_STORAGE_BUCKET_NAME }}' > .env
          echo 'AWS_S3_ACCESS_KEY_ID=${{ secrets.AWS_S3_ACCESS_KEY_ID }}' >> .env
          echo 'AWS_S3_SECRET_ACCESS_KEY=${{ secrets.AWS_S3_SECRET_ACCESS_KEY }}' >> .env
          echo 'AWS_S3_ENDPOINT_URL=${{ secrets.AWS_S3_ENDPOINT_URL }}' >> .env
          echo 'AWS_S3_REGION_NAME=${{ secrets.AWS_S3_REGION_NAME }}' >> .env
          echo 'YETIEN_DEV_MODEL_0_ADDR=${{ secrets.YETIEN_DEV_MODEL_0_ADDR }}' >> .env
          echo 'YETIEN_DEV_MODEL_0_USER=${{ secrets.YETIEN_DEV_MODEL_0_USER }}' >> .env
          echo 'YETIEN_DEV_MODEL_0_PWD=${{ secrets.YETIEN_DEV_MODEL_0_PWD }}' >> .env

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        run: |
          npm install -g pnpm
          pnpm install
      
      - name: Lint
        run: |
          pnpm run lint

      - name: run test
        run: |
          pnpm run test